### ISSUE TITLE
Sketch 69.2, 107504: Window fails to open

### ISSUE THREAD

**Issue by WilNichols** [sonburn/symbol-instance-locator#28]
Started first experiencing this with the named version, but may have been occurring before. Video displays invoking the window, it not opening, and then you can see me open another plugin to show that there are multiple instances of the selected symbol.

It appears to be intermittent. The window wouldn't appear yesterday, but worked again last night. Will happily donate to prioritize a fix; Symbol Instance Locator is an indispensable part of my daily workflow.

[Video](https://www.dropbox.com/s/o4c1fkwyz3pfa3m/symbol%20instance%20locator%20window.mp4?dl=0)

**Comment by cspadazzi** [comment]
Same issue on my end, would also love a fix, integral to my workflow.

**Comment by sonburn** [comment]
@WilNichols sorry for any troubles with the plugin. As you can probably tell, my development on the plugin has slowed due to competing priorities. It's not for lack of interest though, rest assured. I have just published a fix that should improve responsiveness, result accuracy, and better darkmode support. Also includes a fix for Sketch 72. Do you mind giving it a shot?

**Comment by WilNichols** [comment]
@sonburn Absolutely no worries, and I appreciate your followup. I'll get a look!

**Comment by WilNichols** [comment]
So far, so good, and the dark theme changes are further appreciated. Would you prefer I make a new ticket if there are issues with this release?

**Comment by sonburn** [comment]
@WilNichols Glad to hear it. I am going to close this issue, if you run into anything else, please do create a new one.
